name: Create Release Archive
on:
  release:
    types: [prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'cozy-campfire-plus.zip'
        exclusions: '*.git* .editorconfig'
